public enum Location 
{
    MGU_K,
    MGU_H,
    ICE,
    EnergyStore,
    Gearbox,
    TurboCharger,
    ControlElectronics,
    FrontLeftWing,
    FrontRightWing,
    RearWing,
    Underbody,
    FrontLeftWheel,
    FrontLeftBrake,
    FrontRightWheel,
    FrontRightBrake,
    RearLeftWheel,
    RearLeftBrake,
    RearRightWheel,
    RearRightBrake,
    LeftSidepod,
    RightSidepod,
    
}